server:
  port: 8080
  shutdown: graceful

spring:
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  config:
    import: optional:file:.env[.properties]

  sql:
    init:
      mode: always

decorator:
  datasource:
    p6spy:
      enable-logging: true
